#!/bin/bash

echo "🎯 Testing Element Removal: Posts 1-2 → Posts 3-100+"
echo "=================================================="
echo ""

if curl -s http://localhost:3000 > /dev/null; then
    echo "✅ Server running at http://localhost:3000"
    echo ""
else
    echo "❌ Server not running. Run: npm run dev"
    exit 1
fi

echo "🧪 Test Element Removal When Scrolling:"
echo ""
echo "BEFORE SCROLLING:"
echo "=================="
echo "Elements tab shows:"
echo "  <div data-virtual-row=\"0\" data-in-dom=\"true\">"
echo "    <article data-post-id=\"1\">Post #1</article>"
echo "    <article data-post-id=\"2\">Post #2</article>"
echo "  </div>"
echo ""
echo "Debug panel shows:"
echo "  🎴 DOM Cards: 2"
echo "  ✗ Removed: 46"
echo ""

echo "AFTER SCROLLING DOWN:"
echo "======================"
echo "Elements tab will show:"
echo "  ❌ Row 0 disappears!"
echo "  ✅ New rows appear:"
echo "    <div data-virtual-row=\"1\" data-in-dom=\"true\">"
echo "      <article data-post-id=\"3\">Post #3</article>"
echo "      <article data-post-id=\"4\">Post #4</article>"
echo "    </div>"
echo "    <div data-virtual-row=\"2\" data-in-dom=\"true\">"
echo "      <article data-post-id=\"5\">Post #5</article>"
echo "      <article data-post-id=\"6\">Post #6</article>"
echo "    </div>"
echo "    ...and so on up to posts 100+"
echo ""

echo "Verification:"
echo "=============="
echo "1. Search Elements: data-post-id=\"1\" → 0 results (REMOVED!)"
echo "2. Search Elements: data-post-id=\"50\" → 1 result (ADDED!)"
echo "3. Console: document.querySelectorAll('[data-post-id]').length → ~4-6"
echo "4. Debug panel: ✗ Removed count increases"
echo ""

echo "Console Commands:"
echo "=================="
echo "# Check current posts in DOM:"
echo "Array.from(document.querySelectorAll('[data-post-id]')).map(el => el.getAttribute('data-post-id'))"
echo ""
echo "# Count DOM elements:"
echo "document.querySelectorAll('[data-post-id]').length"
echo ""

echo "Expected Results:"
echo "=================="
echo "Scroll Position    | Posts in DOM | Removed"
echo "-------------------|--------------|---------"
echo "Top (initial)      | 1, 2         | 46"
echo "Scroll down 1x     | 3, 4, 5, 6   | 44"
echo "Scroll down 10x    | 21-30        | 18"
echo "Scroll down 20x    | 41-50        | 0 (all visible)"
echo ""

echo "✅ SUCCESS INDICATORS:"
echo "======================="
echo "✓ Posts 1-2 disappear from Elements tab"
echo "✓ Posts 3-100+ appear in Elements tab"
echo "✓ DOM count stays small (~2-6)"
echo "✓ Debug panel shows 'Removed' increasing"
echo "✓ Smooth 60 FPS scrolling"
echo ""

echo "🎯 This proves virtualization removes elements from DOM!"
echo ""
echo "🚀 Scroll down now and watch the magic happen!"